name = "aoc_2024_julia"
uuid = "bf703a7c-7fb4-42c8-89fe-ef746cde3290"
authors = ["Theo Garefalakis <tgaref@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "0.18.20"
